stages:
  - build

before_script:
  - powershell -Command "Set-Content .env '' -Encoding utf8"
  - powershell -Command "Add-Content .env 'LLM_PROVIDER=$env:LLM_PROVIDER' -Encoding utf8"
  - powershell -Command "Add-Content .env 'LLM_API_KEY=$env:LLM_API_KEY' -Encoding utf8"

build:
  stage: build
  script:
    - docker-compose down --remove-orphans
    - docker-compose build --no-cache
    - docker-compose push
    - docker-compose up -d --force-recreate
    - docker image prune -f