stages:
  - before_script
  - build

before_script:
  - echo "LLM_PROVIDER=$LLM_PROVIDER" >> .env
  - echo "LLM_API_KEY=$LLM_API_KEY" >> .env

build:
  stage: build
  script:
    - docker-compose down --remove-orphans
    - docker-compose build --no-cache
    - docker-compose push
    - docker-compose up -d --force-recreate
    - docker image prune -f