stages:
  - build

build:
  stage: build
  script:
    - docker-compose down --remove-orphans
    - docker-compose build --no-cache
    - docker-compose push
    - docker-compose up -d --force-recreate
    - docker image prune -f